apiVersion: traefik.io/v1alpha1  # Для новых версий Traefik (3.x) используется traefik.io [citation:3]
kind: IngressRouteTCP
metadata:
  name: valkey-ingress-tcp
  namespace: valkey 
spec:
  entryPoints:
    - valkey
  routes:
    - match: HostSNI(`*`)
      services:
        - name: valkey-service
          port: 6379