apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulse 

helmCharts:
  - name: pulse
    repo: https://rcourtman.github.io/Pulse
    version: 6.0.1 
    releaseName: pulse
    namespace: pulse
    valuesFile: values.yaml
    includeCRDs: true
resources:
  - base/cr.yaml
  - base/crb.yaml
  - base/sa.yaml
  - base/ingress-route.yaml
  - base/ds.yaml