apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: certificate-chain
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: 'certificate-chain'
        key: 'ca.crt'
  target:
    configMap:
      key: 'ca.crt'
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: '1'
        labels:
          app.kubernetes.io/component: 'trust-bundle'
    additionalFormats:
      jks:
        key: 'ca.jks'
        password: 'changeit'
      pkcs12:
        key: 'ca.p12'
        password: 'changeit'
    namespaceSelector:
      matchLabels:
        cert-manager.io/inject-cert: 'true'
