apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    path: kubernetes/resources/argocd
    repoURL: 'https://github.com/DuraCHYo/homelab-scripts'
    targetRevision: master
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        cert-manager.io/inject-cert: 'true'
