apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtproxy-healthcheck
  namespace: argocd
spec:
  destination:
    namespace: mtproxy-healthcheck
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/DuraCHYo/mtproxy-healthcheck.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
