apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/resources/victoria-metrics
    repoURL: https://github.com/DuraCHYo/homelab-scripts
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        cert-manager.io/inject-cert: 'true'
