apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.72.5
    releaseName: victoria-metrics
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - base/ingress-route.yaml
  - base/proxmox-host-node-exporter.yaml
