- name: Update cluster nodes
  apt:
    update_cache: yes

- name: Enable ipv4_ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Disable SWAP (k8s requirement)
  block:
    - name: Disable SWAP in runtime
      ansible.builtin.command: swapoff -a

    - name: Disable SWAP in fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'

- name: proxmox and k3s required packages installation
  block:
    - name: Install qemu-guest-agent package
      apt:
        name: qemu-guest-agent
        state: present
      when: install_qemu_guest_agent

    - name: Enable and start qemu-guest-agent service
      systemd_service:
        name: qemu-guest-agent
        enabled: true
        masked: false
        state: started
      when:
        - install_qemu_guest_agent
        - enable_qemu_guest_agent | default(true)

    - name: Install iptables
      apt:
        name: iptables
        state: present

- name: Download k3s installation script
  get_url:
    url: 'https://get.k3s.io'
    dest: '/tmp/k3s-install.sh'
    mode: '0755'
    timeout: 30
  register: download_result
  failed_when:
    - download_result is failed
    - download_result.status_code != 200

- name: Install k3s on master
  environment:
    INSTALL_K3S_VERSION: '{{ k3s_version }}'
    K3S_KUBECONFIG_MODE: '644'
  shell: /tmp/k3s-install.sh
  when: inventory_hostname in groups['masters']

- name: Get token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token
  when: inventory_hostname in groups['masters']

- name: Set fact with decoded token
  set_fact:
    k3s_token: "{{ node_token['content'] | b64decode }}"
  when: inventory_hostname in groups['masters']

- name: Deploy worker nodes
  block:
    - name: Join worker nodes to cluster
      environment:
        INSTALL_K3S_VERSION: '{{ k3s_version }}'
        K3S_URL: "https://{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}:6443"
        K3S_TOKEN: "{{ hostvars[groups['masters'][0]]['k3s_token'] | trim }}"
      shell: /tmp/k3s-install.sh
      when: inventory_hostname in groups['workers']

    - name: Label worker nodes
      shell: "kubectl label node {{ item | replace('.','') }} node-role.kubernetes.io/worker=true --overwrite"
      delegate_to: "{{ groups['masters'][0] }}"
      loop: "{{ groups['workers']}}"
      run_once: true
    - name: Taint master node
      shell: "kubectl taint nodes {{ item | replace('.','') }} lab.kubernetes.io/control-plane=true:NoSchedule"
      delegate_to: "{{ groups['masters'][0] }}"
      loop: "{{ groups['masters']}}"
      run_once: true

- name: Ensure k3s-agent is running and enabled
  systemd:
    name: k3s-agent
    state: started
    enabled: yes
    daemon_reload: yes
  when: inventory_hostname in groups['workers']

- name: Give chmod to kubectl on {{ ansible_facts.hostname }}
  file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: 'o+r'
  when: inventory_hostname in groups['masters']

- name: Change kubeconfig master ip
  command: "sed -i 's/127.0.0.1/{{ ansible_facts.default_ipv4.address }}/g' /etc/rancher/k3s/k3s.yaml"
  when: inventory_hostname in groups['masters']

- name: Put kubeconfig to ~/.kube/config
  fetch:
    src: '/etc/rancher/k3s/k3s.yaml'
    dest: '/Users/depishev/.kube/config'
    flat: true
  when: inventory_hostname in groups['masters']

- name: Copy mkcerts from local to master
  copy:
    src: '../../certs/{{ item | basename }}'
    dest: '/home/ubuntu/{{ item | basename }}'
  loop:
    - ../../certs/_wildcard.lab.local-key.pem
    - ../../certs/_wildcard.lab.local.pem
  when: inventory_hostname in groups['masters']

- name: Read certificate files from remote hosts
  slurp:
    src: '/home/ubuntu/_wildcard.lab.local.pem'
  register: cert_file
  when: inventory_hostname in groups['masters']

- name: Read key files from remote hosts
  slurp:
    src: '/home/ubuntu/_wildcard.lab.local-key.pem'
  register: key_file
  when: inventory_hostname in groups['masters']

- name: Set facts with certificate content
  set_fact:
    cert_content: '{{ cert_file.content }}'
    key_content: '{{ key_file.content }}'
  when: inventory_hostname in groups['masters']

- name: Generate TLS Ingress Secret from template
  template:
    src: ../templates/wildcard-lab-local-tls.yaml.j2
    dest: /tmp/tls-secret.yaml
  vars:
    tls_crt_b64: '{{ cert_content }}'
    tls_key_b64: '{{ key_content }}'
  when: inventory_hostname in groups['masters']

- name: Generate TLS Ingress tlsstore from template
  template:
    src: ../templates/tlsstore.yaml.j2
    dest: /tmp/tlsstore.yaml
  when: inventory_hostname in groups['masters']

- name: Apply Secret using kubectl
  shell: kubectl apply -f /tmp/tls-secret.yaml && kubectl apply -f /tmp/tlsstore.yaml
  changed_when: true
  when: inventory_hostname in groups['masters']

- name: Clean up temporary file
  file:
    path: /tmp/tls-secret.yaml
    state: absent

- import_tasks: tasks/deploy-argocd.yaml

- name: Wait until argocd up
  uri:
    url: 'https://argocd.lab.local/healthz'
    validate_certs: 'false'
  register: result
  until: 'result.status == 200'
  retries: 18
  delay: 10
  when: inventory_hostname in groups['masters']
