- name: Install and configure nginx
  hosts: s1server
  handlers:
    - name: Reload nginx
      include_tasks: ../handlers/reload-nginx.yaml
  tasks:
    - import_tasks: tasks/install-node-exporter.yaml
      when: install_node_exporter

    - name: Disable SWAP (k8s requirement)
      block:
        - name: Disable SWAP in runtime
          ansible.builtin.command: swapoff -a

        - name: Disable SWAP in fstab
          ansible.builtin.replace:
            path: /etc/fstab
            regexp: '^([^#].*?\sswap\s+.*)$'
            replace: '# \1'

    - name: Install nginx from apt
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Install certutils
      ansible.builtin.apt:
        name: libnss3-tools
        state: present

    - name: Download mkcert util
      ansible.builtin.get_url:
        url: 'https://dl.filippo.io/mkcert/latest?for=linux/amd64'
        dest: '/usr/local/bin/mkcert'
        mode: '0755'

    - name: Install to CARoot
      command: mkcert -install

    - name: Generate certs for CA
      command: mkcert -key-file /etc/pve/local/mkcert.key -cert-file /etc/pve/local/mkcert.pem {{ ansible_facts.hostname }} {{ ansible_facts.default_ipv4.address }} localhost 127.0.0.1 "*.lab.local"

    - name: Get CARoot dir
      command: mkcert --CAROOT
      register: caroot_path

    - name: Generate client certificate
      shell: mkcert *.lab.local

    - name: Get RootCA for install on trustedCA store
      ansible.builtin.fetch:
        src: '{{ item }}'
        dest: '/Users/depishev/Documents/vscode/homelab-scripts/certs/{{ item | basename }}'
        flat: true
      loop:
        - '{{ caroot_path.stdout }}/rootCA.pem'
        - '{{ caroot_path.stdout }}/rootCA-key.pem'
        - '{{ ansible_facts.env.HOME }}/_wildcard.lab.local-key.pem'
        - '{{ ansible_facts.env.HOME }}/_wildcard.lab.local.pem'

    - name: Config server for running nginx
      block:
        - name: Remove default config
          ansible.builtin.file:
            path: /etc/nginx/sites-enabled/default
            state: absent

        - name: Deploy config to server
          ansible.builtin.template:
            src: ../templates/nginx.conf.j2
            dest: /etc/nginx/conf.d/proxmox.conf
          notify: Reload nginx
